### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by markgriffey** [YashMarmat/Instagram-clone-with-FLASK#1] opened 2023-10-04 18:01 UTC
I am trying to test out the app locally and am getting stuck at the "flask db init" step in the readme file. I am getting this error: ImportError: cannot import name 'userRoute' from 'app.userRoute' (...igclone/app/userRoute/__init__.py)

**Comment by markgriffey** [comment] 2023-10-04 19:09
OK, that previous issue was my mistake, but I am now getting this error: "Detected factory 'create_app' in module 'app', but could not call it without arguments. Use 'app:create_app(args)' to specify arguments."

**Comment by YashMarmat** [comment] 2023-10-05 06:16
Hi, @markgriffey I tried running the whole application on a different machine following the steps present in README.md, and it's working fine for me. Can you please tell me after which step/command of readme you are facing this error, also cross-check if you have run all the steps present in readme.

Also, make sure you are in the correct directory should be like this (for example when running `flask run` and other commands)
(myenv) C:\testing\Instagram-clone-with-FLASK>flask run

**Comment by markgriffey** [comment] 2023-10-05 19:30
Thank you. I was in the correct directory and eventually got it to work. I'm pretty sure the issue is that I hadn't installed Flask-SQLAlchemy-3 correctly.

**Comment by markgriffey** [comment] 2023-10-05 22:36
Also, would you happen to know why I am encountering a 404 error when I try to log in? This is what I'm getting onscreen at my local host: http://localhost:5000/

{
  "msg": "Not Found"
}

**Comment by YashMarmat** [comment] 2023-10-06 04:31
Glad it worked for you, for the not found issue. The problem is we do not have any HTML to serve on the page, so this is getting returned. Because the app has APIs only (and no Frontend), I would suggest you to use Postman and test the APIs there. Attaching a screenshot for example below: (also import the API collection in your Postman app, location is mentioned in readme.md)

![image](https://github.com/YashMarmat/Instagram-clone-with-FLASK/assets/59337853/f3662a4b-1d79-4159-9b9d-1951a285aa24)

**Comment by YashMarmat** [comment] 2023-10-08 08:31
I hope this clears up your doubts, I'm closing this issue. Please create a new one in case of any other issue.

**Closed as completed by YashMarmat** 2023-10-08 08:31 UTC
